version: 2

before:
  hooks:
    - go generate ./...

builds:
  - binary: speaches-ui
    ldflags:
      - -s
      - -w
      - -extldflags
      - -static
    flags:
      - -a
      - -installsuffix
      - cgo
    env:
      - CGO_ENABLED=0
    goarch:
      - amd64
      - arm64
      - riscv64
    goos:
      - linux
      - windows
      - darwin
    mod_timestamp: "{{ .CommitTimestamp }}"

dockers:
  - use: buildx
    goos: linux
    goarch: amd64
    image_templates:
      - "tyrm/{{ .ProjectName }}:{{ .Version }}-amd64"
      - "tyrm/{{ .ProjectName }}:latest-amd64"
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
  - use: buildx
    goos: linux
    goarch: arm64
    image_templates:
      - "tyrm/{{ .ProjectName }}:{{ .Version }}-arm64v8"
      - "tyrm/{{ .ProjectName }}:latest-arm64v8"
    build_flag_templates:
      - "--platform=linux/arm64/v8"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
  - use: buildx
    goos: linux
    goarch: riscv64
    image_templates:
      - "tyrm/{{ .ProjectName }}:{{ .Version }}-riscv64"
      - "tyrm/{{ .ProjectName }}:latest-riscv64"
    build_flag_templates:
      - "--platform=linux/riscv64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"

docker_manifests:
  - name_template: "tyrm/{{ .ProjectName }}:latest"
    image_templates:
      - "tyrm/{{ .ProjectName }}:latest-amd64"
      - "tyrm/{{ .ProjectName }}:latest-arm64v8"
      - "tyrm/{{ .ProjectName }}:latest-riscv64"
  - name_template: "tyrm/{{ .ProjectName }}:{{ .Version }}"
    image_templates:
      - "tyrm/{{ .ProjectName }}:{{ .Version }}-amd64"
      - "tyrm/{{ .ProjectName }}:{{ .Version }}-arm64v8"
      - "tyrm/{{ .ProjectName }}:{{ .Version }}-riscv64"

checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_SHA256SUMS'
  algorithm: sha256

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^deployments:'

gitea_urls:
  api: https://tyr.codes/api/v1/
  download: https://tyr.codes
